name: Jekyll Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
        echo '>>>ls:'
        ls ${{ github.workspace }}/_site
        echo '>>>pwd:'
        echo ${{ github.workspace }}/_site
        
      
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.HB4_KEY }} 
        known_hosts: ${{ secrets.HB4_FINGER }}
        


        
    - name: make _site.tgz
      run: |
        cd ${{ github.workspace }} && \
        tar -zcvf _site.tgz _site  
        
    - name: rsync
      run: |
        rsync -ah --stats \
        ${{ github.workspace }}/_site.tgz \
        ${{ secrets.HB4_USER }}@${{ secrets.HB4_HOST }}:/root/_ci
    
        
    - name: deploy
      run: |
        ssh -t ${{ secrets.HB4_USER }}@${{ secrets.HB4_HOST }} "\
        cd /root/_ci && echo 'Removing old _site ...' && \
        rm -rf _site && echo 'Unzipping ...' && \
        tar -zxf _site.tgz && echo 'Deploying ...' &&\
        rsync -ah --stats --delete  _site/ /var/www/atutongxue.com && echo 'Chowning ...' && \
        chown -R root:root /var/www/atutongxue.com && echo 'Deploy ok!'  \
        "


        
    - name: done
      run: |
        echo 'All done!'
      
